apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # You can change this if needed
